# Generated by Django 5.0.4 on 2024-04-06 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telefono',
            name='empleado',
        ),
        migrations.RenameField(
            model_name='empleado',
            old_name='apellido',
            new_name='apellidos',
        ),
        migrations.RenameField(
            model_name='empleado',
            old_name='nombre',
            new_name='nombres',
        ),
        migrations.DeleteModel(
            name='Email',
        ),
        migrations.DeleteModel(
            name='Telefono',
        ),
    ]
