# Generated by Django 5.0.4 on 2024-04-07 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleados', '0002_remove_telefono_empleado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Telefono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=4)),
                ('numero', models.CharField(max_length=20)),
                ('indicativo', models.CharField(max_length=10)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telefonos', to='empleados.empleado')),
            ],
        ),
    ]
