# Generated by Django 5.0.4 on 2024-04-09 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telefonos', '0002_alter_telefono_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telefono',
            name='tipo',
            field=models.CharField(max_length=10),
        ),
    ]
